# Generated by Django 4.2.3 on 2025-08-05 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advisers/', verbose_name='عکس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل')),
                ('age', models.PositiveIntegerField(verbose_name='سن')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=6, verbose_name='جنسیت')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='موقعیت')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس دقیق')),
                ('bachelor_field', models.CharField(max_length=100, verbose_name='رشته تحصیلی کارشناسی')),
                ('bachelor_year', models.PositiveIntegerField(verbose_name='سال فارغ التحصیلی کارشناسی')),
                ('master_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='رشته تحصیلی کارشناسی ارشد')),
                ('master_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال فارغ التحصیلی کارشناسی ارشد')),
                ('phd_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='رشته تحصیلی دکتری')),
                ('phd_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال فارغ التحصیلی دکتری')),
                ('is_unemployed', models.BooleanField(default=False, verbose_name='آیا در حال حاضر مشغول به کار هستید؟')),
                ('current_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='شغل فعلی')),
                ('current_organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='محل کار')),
                ('current_description', models.TextField(blank=True, null=True, verbose_name='توضیحات شغلی')),
                ('work_preferences', models.JSONField(blank=True, default=list, verbose_name='مایل به کار')),
                ('specialties', models.JSONField(default=list, verbose_name='زمینه های تخصصی')),
                ('consultation_methods', models.JSONField(default=list, verbose_name='روش های مشاوره')),
                ('accepted_terms', models.BooleanField(default=False, verbose_name='قوانین و مقررات را قبول دارم')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایش به عنوان مشاور برتر')),
            ],
            options={
                'verbose_name': 'مشاور',
                'verbose_name_plural': 'مشاوران',
            },
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_name', models.CharField(max_length=255, verbose_name='نام کافه')),
                ('cafe_type', models.CharField(choices=[('traditional restaurant', 'رستوران سنتی'), ('cafe', 'کافه'), ('cafe restaurant', 'کافه رستوران'), ('book cafe', 'کافه کتاب'), ('other', 'سایر')], max_length=30, verbose_name='نوع کافه')),
                ('address', models.TextField(verbose_name='آدرس دقیق')),
                ('size', models.PositiveIntegerField(verbose_name='وسعت کافه')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('menu_file', models.FileField(blank=True, null=True, upload_to='menus/', verbose_name='منو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات اضافه')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cafes/', verbose_name='لوگوی کافه')),
                ('has_parking', models.BooleanField(blank=True, default=False, verbose_name='پارکینگ')),
                ('has_workspace', models.BooleanField(blank=True, default=False, verbose_name='فضای کار')),
                ('has_disabled_access', models.BooleanField(blank=True, default=False, verbose_name='دسترسی معلولین')),
                ('accepted_terms', models.BooleanField(blank=True, default=False, verbose_name='قوانین و مقررات را قبول دارم')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایش در صفحه درباره ما')),
            ],
            options={
                'verbose_name': 'کافه',
                'verbose_name_plural': 'کافه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='کلید نشست')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام اهداکننده')),
                ('donor_phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('donor_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ (تومان)')),
                ('donation_type', models.CharField(choices=[('charity', 'خیریه'), ('support', 'حمایت از پروژه'), ('general', 'حمایت عمومی')], default='charity', max_length=20, verbose_name='نوع حمایت')),
                ('message', models.TextField(blank=True, null=True, verbose_name='پیام')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='حمایت ناشناس')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('completed', 'پرداخت شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'حمایت مالی',
                'verbose_name_plural': 'حمایت\u200cهای مالی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='شماره سفارش')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ کل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده'), ('failed', 'ناموفق')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('code', models.SmallIntegerField()),
                ('expration_code', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن')),
                ('plan_type', models.CharField(choices=[('phone', 'تلفنی'), ('inperson', 'حضوری')], max_length=10, verbose_name='نوع پلن')),
                ('duration', models.IntegerField(verbose_name='مدت زمان (دقیقه)')),
                ('extra_time', models.IntegerField(verbose_name='زمان اضافه (دقیقه)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پلن',
                'verbose_name_plural': 'پلن\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پادکست')),
                ('category', models.CharField(choices=[('روابط عاطفی', 'روابط عاطفی'), ('خانواده', 'خانواده'), ('اضطراب و استرس', 'اضطراب و استرس'), ('افسردگی', 'افسردگی'), ('مسائل شغلی', 'مسائل شغلی'), ('بحران\u200cهای روانی', 'بحران\u200cهای روانی'), ('سایر', 'سایر')], max_length=50, verbose_name='موضوع اصلی')),
                ('keywords', models.CharField(max_length=100, verbose_name='کلمات کلیدی')),
                ('audio_file', models.FileField(upload_to='podcasts/', verbose_name='فایل صوتی')),
                ('accepted_rules', models.BooleanField(verbose_name='تایید قوانین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین')),
            ],
            options={
                'verbose_name': 'پادکست',
                'verbose_name_plural': 'پادکست\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی مالک')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('cafe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='us.cafe')),
            ],
            options={
                'verbose_name': 'مالک',
                'verbose_name_plural': 'مالکان',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت واحد')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت کل')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='us.order', verbose_name='سفارش')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us.plan', verbose_name='پلن')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certificates/', verbose_name='مدارک')),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='us.adviser')),
            ],
            options={
                'verbose_name': 'مدرک',
                'verbose_name_plural': 'مدرک\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='us.cart', verbose_name='سبد خرید')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us.plan', verbose_name='پلن')),
            ],
            options={
                'verbose_name': 'آیتم سبد خرید',
                'verbose_name_plural': 'آیتم\u200cهای سبد خرید',
            },
        ),
    ]
