# Generated by Django 4.2.3 on 2025-07-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='current_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات شغلی'),
        ),
    ]
