# Generated by Django 4.2.3 on 2025-07-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0002_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='adviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('age', models.PositiveIntegerField(verbose_name='سن')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=6, verbose_name='جنسیت')),
                ('location', models.CharField(max_length=255, verbose_name='موقعیت')),
                ('bachelor_field', models.CharField(max_length=100, verbose_name='رشته تحصیلی کارشناسی')),
                ('bachelor_year', models.PositiveIntegerField(verbose_name='سال فارغ التحصیلی کارشناسی')),
                ('master_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='رشته تحصیلی کارشناسی ارشد')),
                ('master_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال فارغ التحصیلی کارشناسی ارشد')),
                ('phd_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='رشته تحصیلی دکتری')),
                ('phd_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال فارغ التحصیلی دکتری')),
                ('is_unemployed', models.BooleanField(default=False)),
                ('current_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='شغل فعلی')),
                ('current_organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='محل کار')),
                ('current_description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('work_preferences', models.JSONField(blank=True, default=list, verbose_name='مایل به کار')),
                ('specialties', models.JSONField(default=list, verbose_name='زمینه های تخصصی')),
                ('consultation_methods', models.JSONField(default=list, verbose_name='روش های مشاوره')),
                ('accepted_terms', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_name', models.CharField(max_length=255, verbose_name='نام کافه')),
                ('cafe_type', models.CharField(choices=[('traditional', 'کافه سنتی'), ('modern', 'کافه مدرن'), ('roastery', 'رستری و تخصصی'), ('book', 'کافه کتاب'), ('other', 'سایر')], max_length=20, verbose_name='نوع کافه')),
                ('address', models.TextField(verbose_name='آدرس دقیق')),
                ('size', models.PositiveIntegerField(verbose_name='وسعت کافه')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('menu_file', models.FileField(upload_to='menus/', verbose_name='منو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات اضافه')),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_live_music', models.BooleanField(default=False)),
                ('has_outdoor', models.BooleanField(default=False)),
                ('has_hookah', models.BooleanField(default=False)),
                ('has_workspace', models.BooleanField(default=False)),
                ('serves_breakfast', models.BooleanField(default=False)),
                ('has_disabled_access', models.BooleanField(default=False)),
                ('accepted_terms', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی مالک')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('cafe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='us.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certificates/', verbose_name='مدارک')),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='us.adviser')),
            ],
        ),
    ]
