# Generated by Django 4.2.3 on 2025-07-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0002_alter_adviser_current_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advisers/', verbose_name='عکس'),
        ),
    ]
