# Generated by Django 4.2.3 on 2025-07-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0003_adviser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه درباره ما'),
        ),
    ]
