# Generated by Django 4.2.3 on 2025-07-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0003_adviser_cafe_owner_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='adviser',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='موقعیت'),
        ),
    ]
