# Generated by Django 4.2.3 on 2025-07-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0004_cafe_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cafes/', verbose_name='لوگوی کافه'),
        ),
    ]
