# Generated by Django 4.2.3 on 2025-07-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0004_adviser_latitude_adviser_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='accepted_terms',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_disabled_access',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_hookah',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_live_music',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_outdoor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_parking',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_wifi',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_workspace',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='serves_breakfast',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
