# Generated by Django 4.2.3 on 2025-07-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0005_cafe_latitude_cafe_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس دقیق'),
        ),
    ]
