# Generated by Django 4.2.3 on 2025-07-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0006_adviser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پادکست')),
                ('category', models.CharField(choices=[('روابط عاطفی', 'روابط عاطفی'), ('خانواده', 'خانواده'), ('اضطراب و استرس', 'اضطراب و استرس'), ('افسردگی', 'افسردگی'), ('مسائل شغلی', 'مسائل شغلی'), ('بحران\u200cهای روانی', 'بحران\u200cهای روانی'), ('سایر', 'سایر')], max_length=50, verbose_name='موضوع اصلی')),
                ('keywords', models.CharField(max_length=100, verbose_name='کلمات کلیدی')),
                ('audio_file', models.FileField(upload_to='podcasts/', verbose_name='فایل صوتی')),
                ('accepted_rules', models.BooleanField(verbose_name='تایید قوانین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
    ]
