# Generated by Django 4.2.3 on 2025-07-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0007_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adviser',
            options={'verbose_name': 'مشاور', 'verbose_name_plural': 'مشاوران'},
        ),
        migrations.AlterModelOptions(
            name='cafe',
            options={'verbose_name': 'کافه', 'verbose_name_plural': 'کافه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'مدرک', 'verbose_name_plural': 'مدرک\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'مالک', 'verbose_name_plural': 'مالکان'},
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={'verbose_name': 'پادکست', 'verbose_name_plural': 'پادکست\u200cها'},
        ),
    ]
