# Generated by Django 4.2.3 on 2025-07-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0007_podcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین'),
        ),
    ]
