# Generated by Django 5.2.1 on 2025-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0008_podcast_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین'),
        ),
        migrations.AddField(
            model_name='adviser',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایش به عنوان مشاور برتر'),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='accepted_terms',
            field=models.BooleanField(default=False, verbose_name='قوانین و مقررات را قبول دارم'),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='is_unemployed',
            field=models.BooleanField(default=False, verbose_name='آیا در حال حاضر مشغول به کار هستید؟'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='accepted_terms',
            field=models.BooleanField(blank=True, default=False, verbose_name='قوانین و مقررات را قبول دارم'),
        ),
    ]
