# Generated by Django 4.2.3 on 2025-08-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0008_alter_adviser_options_alter_cafe_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام اهداکننده')),
                ('donor_phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('donor_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ (تومان)')),
                ('donation_type', models.CharField(choices=[('charity', 'خیریه'), ('support', 'حمایت از پروژه'), ('general', 'حمایت عمومی')], default='charity', max_length=20, verbose_name='نوع حمایت')),
                ('message', models.TextField(blank=True, null=True, verbose_name='پیام')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='حمایت ناشناس')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('completed', 'پرداخت شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'حمایت مالی',
                'verbose_name_plural': 'حمایت\u200cهای مالی',
                'ordering': ['-created_at'],
            },
        ),
    ]
